- hosts: jumpbox
  become: yes
  gather_facts: false
#  roles:
#    - osp-networking
#    - osp-keypair
#    - osp-flavor
#    - osp-security_group
# 
  tasks:
#    - name: Install DB Security Group Rules
#      include_role:
#        name: osp-security_group_rule
#        vars_from: db.yml
#
#    - name: Install App Security Group Rules
#      include_role:
#        name: osp-security_group_rule
#        vars_from: app.yml
#
#    - name: Install Frontend Security Group Rules
#      include_role:
#        name: osp-security_group_rule
#        vars_from: front.yml

    - name: Basic Ping
      ping:

    - name: Install DB Server
      include_role:
        name: osp-instances
        vars_from: db.yaml
#
#    - name: Install App Server 1
#      include_role:
#        name: osp-instances
#        vars_from: app1.yaml
#
#    - name: Install App Server 2
#      include_role:
#        name: osp-instances
#        vars_from: app2.yaml
#
#    - name: Install Frontend
#      include_role:
#        name: osp-instances
#        vars_from: frontend.yaml
