---
# vars file for osp-security_group_rule
rules:
   - { security_group: 'db', protocol: 'tcp', port: '5432', protocol: 'tcp' }
   - { security_group: 'db', protocol: 'tcp', port: '22', protocol: 'tcp' }
   - { security_group: 'db', protocol: 'tcp', port: '-1', protocol: 'icmp' }
